config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :dashboards, only: [ :index ]
  resources :users do
    member do
      patch :upload
      delete :remove
    end
  end

  resources :clients do
    member do
      get :cases
    end
  end

  resources :court_cases do
    member do
      get :lawyers
    end
  end

  resources :lawyers
  resources :judges
  resources :tasks
  resources :roles
  resources :categories
  resources :appointments
  resources :services
  resources :invoices do
    get :get_issued_user, on: :collection
    member do
     get :download, defaults: { format: "pdf" }
    end
  end

  get "/profile", to: "users#show_current", as: :profile
  get "invoices/new_item_field", to: "invoices#new_item_field"
  get "/services/:id/price", to: "services#price"
  root "dashboards#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/judge.rb
class Judge < User
  default_scope { joins(:roles).where(roles: { name: [ "judge" ] }) }

  include PgSearch::Model

  pg_search_scope :search_by_keywords,
                  against: [ :name, :court_name ],
                  using: { tsearch: { prefix: true } }

  #------------------------------------Validations------------------------------------------------------

  validates :name, :court_name, presence: true
end

app/controllers/judges_controller.rb
class JudgesController < ApplicationController
  before_action :set_judge, only: [ :show, :edit, :update, :destroy ]

  def index
    @judges = Judge.order(created_at: :desc).page(params[:page]).per(5)
    @judges = @judges.search_by_keywords(params[:query]) if params[:query].present?
    @judges = @judges.where(court_name: params[:court]) if params[:court].present?
  end

  def new
     @judge = Judge.new
  end

  def create
    @judge = Judge.new(judge_params)
    if @judge.save
      @judge.add_role("judge")
      redirect_to judges_path, notice: "Judge was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @judge.update(judge_params)
      redirect_to judges_path, notice: "Judge was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @judge.destroy
    redirect_to judges_path, notice: "Judge was successfully deleted."
  end

  private

  def judge_params
     params.require(:judge).permit(:name, :email, :gender, :court_name, :password, :password_confirmation, :created_at, :updated_at)
  end

  def set_judge
    @judge = Judge.find(params[:id])
  end
end

app/views/judges/_form.html.erb
<section class="section">
  <div class="row">
    <div class="col-lg-12">
        <%= form_with model: @judge, local: true, html: { class: "row g-3" } do |f| %>
          <% if @judge.errors.any? %>
            <div class="col-9">
              <div class="alert alert-danger">
                <h5><%= pluralize(@judge.errors.count, "error") %> prevented this form from saving:</h5>
                <ul class="mb-0">
                  <% @judge.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>
          <div class="col-md-6 mb-3">
            <%= f.label :Name, class: "form-label fw-bold" %>
            <%= f.text_field :name, class: "form-control", disabled: action_name == "show" %>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.label :email, class: "form-label fw-bold" %>
           <%= f.email_field :email, class: "form-control", disabled: action_name == "show" %>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.label :gender, class: "form-label fw-bold" %>
            <%= f.select :gender, options_for_select([['Male', 'male'], ['Female', 'female'], ['Other', 'other']]), { prompt: "Select Gender" }, class: "form-select", disabled: action_name == "show" %>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.label :court_name, class: "form-label fw-bold" %>
            <%= f.text_field :court_name, class: "form-control", disabled: action_name == "show"%>
          </div>
          <div class="col-md-6 mb-3">
            <%= f.label :password, class: "form-label fw-bold" %>
            <%= f.password_field :password, class: "form-control", disabled: action_name == "show" %>
          </div>
          <div class="text-center">
            <%= f.submit "Submit", class: "btn btn-primary" %>
          </div>
        <% end %>
    </div>
  </div>
</section>

app/views/judges/_index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Court Name</th>
      <th scope="col">Created At</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @judges.each do |judge| %>
     <tr style="cursor: pointer;" onclick="window.location='<%= judge_path(judge) %>'">
       <td><%= judge&.name %></td>
       <td><%= judge&.court_name %></td>
       <td><%= judge&.created_at.strftime('%Y-%m-%d') %></td>
       <td onclick="event.stopPropagation();" class="position-relative">
        <div class="dropdown">
         <button class="btn btn-link text-dark p-0" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-three-dots"></i>
         </button>
         <ul class="dropdown-menu">
          <li>
           <%= button_to judge_path(judge), method: :delete, data: { confirm: "Are you sure?" }, form: { style: "display:inline;" }, class: "dropdown-item text-black px-3 py-1 text-center", style: "font-size: 0.85rem; width: 100px;" do %>
             Delete
           <% end %>
          </li>
         </ul>
        </div>
       </td>

     </tr>
    <% end %>
  </tbody>
</table>
<div class="mt-3 d-flex justify-content-end">
  <%= paginate @judges %>
</div>

app/views/judges/edit.html.erb
<main id="main" class="main">
  <section class="section">
    <div class="card">
     <div class="card-body">
        <h5 class="card-title fw-bold mb-3 d-flex justify-content-between align-items-center">
         <%= @judge&.name %>
         <%= link_to judges_path, class: "text-secondary" do %>
            <i class="bi bi-x-circle fs-2"></i>
         <% end %>
        </h5>
        <%= render "judges/form" %>
      </div>
    </div>
  </section>
</main>

app/views/judges/index.html.erb
<main id="main" class="main">
 <%= render 'shared/flash' %>
  <section class="section">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title fw-bold">Judges</h5>
         <div class="d-flex justify-content-end mb-4">
           <%= link_to 'New Judge', new_judge_path, class: 'btn btn-primary' %>
         </div>
         <div class="mb-4">
          <%= form_with url: judges_path, method: :get, data: { controller: "search", turbo_frame: "_top" } do %>
            <div class="d-flex flex-wrap gap-2 mb-4">
               
            </div>

            <div class="d-flex justify-content-between align-items-center flex-wrap gap-2">
              <%= search_field_tag :query, params[:query], placeholder: "Search...", class: "form-control", style: "width: 220px;", data: { action: "input->search#search" } %>
            </div>
         <% end %>
        </div>
         <%= render "judges/index" %>
      </div> 
    </div>
  </section>
</main>

app/views/judges/new.html.erb
<main id="main" class="main">
  <section class="section">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title fw-bold">New Judge</h5>
        <%= render "judges/form" %>
      </div>
    </div>
  </section>
</main>

app/views/judges/show.html.erb
<main id="main" class="main">
  <section class="section">
    <div class="card">
     <div class="card-body">
        <h5 class="card-title fw-bold mb-5 d-flex justify-content-between align-items-center">
         <%= @judge&.name %>
         <%= link_to edit_judge_path(@judge), class: "text-primary" do %>
           <i class="bi bi-pencil-square fs-4"></i>
         <% end %>
        </h5>
          <%= render "judges/form" %>
      </div>
    </div>
  </section>
</main>